# =============================================================================
# Dockerfile for Vite React Application
# Generated by Opsera Code-to-Cloud v0.6
# Learning #211: Vite env vars must be passed as build-time ARGs
# =============================================================================

# -----------------------------------------------------------------------------
# Stage 1: Build
# -----------------------------------------------------------------------------
FROM node:20-alpine AS builder

WORKDIR /app

# Install dependencies first (layer caching optimization)
COPY package*.json ./

# Learning #427: Always regenerate package-lock.json to avoid npm ci failures
RUN npm install

# Copy source code
COPY . .

# Build arguments for Vite environment variables
# Add your VITE_* variables here as ARG and pass them during build
# Example: ARG VITE_API_URL
#          ENV VITE_API_URL=$VITE_API_URL

# Build the application
RUN npm run build

# -----------------------------------------------------------------------------
# Stage 2: Production
# -----------------------------------------------------------------------------
FROM nginx:alpine AS production

# Learning #153: Add security hardening
RUN addgroup -g 1001 -S appgroup && \
    adduser -u 1001 -S appuser -G appgroup

# Copy built assets from builder
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Learning #089: Health check endpoint
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1

# Expose port
EXPOSE 8080

# Run as non-root user
USER appuser

CMD ["nginx", "-g", "daemon off;"]
